"""add program instances for tracking scheduled programs

Revision ID: 08a544b30ee4
Revises: 93e5d356f113
Create Date: 2025-12-20 19:07:36.728514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a544b30ee4'
down_revision = '93e5d356f113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['user_gyms.id'], name='fk_program_instances_gym_id'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name='fk_program_instances_program_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_program_instances_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_scheduled_days_instance_id', 'program_instances', ['instance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scheduled_days_instance_id', type_='foreignkey')
        batch_op.drop_column('instance_id')

    op.drop_table('program_instances')
    # ### end Alembic commands ###
