"""add_user_goals_table

Revision ID: 0d4ed9ba0b5a
Revises: f2a3b4c5d6e7
Create Date: 2025-12-22 22:07:02.323640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4ed9ba0b5a'
down_revision = 'f2a3b4c5d6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('target_body_fat', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('target_chest', sa.Float(), nullable=True),
    sa.Column('target_waist', sa.Float(), nullable=True),
    sa.Column('target_hips', sa.Float(), nullable=True),
    sa.Column('target_left_arm', sa.Float(), nullable=True),
    sa.Column('target_right_arm', sa.Float(), nullable=True),
    sa.Column('target_left_thigh', sa.Float(), nullable=True),
    sa.Column('target_right_thigh', sa.Float(), nullable=True),
    sa.Column('target_left_calf', sa.Float(), nullable=True),
    sa.Column('target_right_calf', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_goals')
    # ### end Alembic commands ###
