"""add_profile_picture_to_user_profile

Revision ID: 326bdfc72ea9
Revises: 0d4ed9ba0b5a
Create Date: 2025-12-22 22:14:28.031135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326bdfc72ea9'
down_revision = '0d4ed9ba0b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
