"""add gym to scheduled days

Revision ID: 93e5d356f113
Revises: a7b973121125
Create Date: 2025-12-20 18:58:52.151047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e5d356f113'
down_revision = 'a7b973121125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_scheduled_days_gym_id', 'user_gyms', ['gym_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scheduled_days_gym_id', type_='foreignkey')
        batch_op.drop_column('gym_id')

    # ### end Alembic commands ###
