"""add_missing_indexes_for_optimization

Revision ID: 9f40e0ea0323
Revises: 326bdfc72ea9
Create Date: 2025-12-22 22:34:33.338862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f40e0ea0323'
down_revision = '326bdfc72ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_metric_history', schema=None) as batch_op:
        batch_op.create_index('idx_user_recorded', ['user_id', 'recorded_at'], unique=False)

    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.create_index('idx_week', ['week_id'], unique=False)

    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.create_index('idx_series', ['series_id'], unique=False)

    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.create_index('idx_program', ['program_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.drop_index('idx_program')

    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.drop_index('idx_series')

    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.drop_index('idx_week')

    with op.batch_alter_table('body_metric_history', schema=None) as batch_op:
        batch_op.drop_index('idx_user_recorded')

    # ### end Alembic commands ###
