"""add instance exercise weight overrides

Revision ID: a5c47458a0f3
Revises: 08a544b30ee4
Create Date: 2025-12-22 15:29:06.000295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c47458a0f3'
down_revision = '08a544b30ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_exercise_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('program_exercise_id', sa.Integer(), nullable=False),
    sa.Column('custom_weights', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['program_instances.id'], name='fk_instance_weights_instance_id'),
    sa.ForeignKeyConstraint(['program_exercise_id'], ['program_exercises.id'], name='fk_instance_weights_prog_ex_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_exercise_weights')
    # ### end Alembic commands ###
