"""add scheduled days for calendar

Revision ID: a7b973121125
Revises: c558ea5d4ef4
Create Date: 2025-12-20 18:22:25.682607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b973121125'
down_revision = 'c558ea5d4ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_day_id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.create_index('idx_user_date', ['user_id', 'calendar_date'], unique=False)
        batch_op.create_index('idx_user_program_date', ['user_id', 'program_id', 'calendar_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.drop_index('idx_user_program_date')
        batch_op.drop_index('idx_user_date')

    op.drop_table('scheduled_days')
    # ### end Alembic commands ###
