"""post_test_2_updates

Revision ID: c0a6e00d04f7
Revises: 63527827c75e
Create Date: 2025-12-18 22:02:53.198667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a6e00d04f7'
down_revision = '63527827c75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_equipment_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['equipment_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_category_mapping')
    op.drop_table('equipment_adjustments')
    op.drop_table('exercise_categories')
    with op.batch_alter_table('master_equipment', schema=None) as batch_op:
        batch_op.drop_column('suggested_sets')
        batch_op.drop_column('suggested_reps')
        batch_op.drop_column('suggested_dropset')

    with op.batch_alter_table('master_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.drop_column('sub_muscle_groups')
        batch_op.drop_column('suggested_sets')
        batch_op.drop_column('suggested_reps')
        batch_op.drop_column('suggested_dropset')

    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_superset', sa.Boolean(), nullable=False))

    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.drop_column('superset_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superset_group', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.drop_column('has_superset')

    with op.batch_alter_table('master_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_dropset', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('suggested_reps', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('suggested_sets', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sub_muscle_groups', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('master_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_dropset', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('suggested_reps', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('suggested_sets', sa.INTEGER(), nullable=True))

    op.create_table('exercise_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_adjustments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_category_mapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['exercise_categories.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_equipment_variations')
    op.drop_table('equipment_variations')
    # ### end Alembic commands ###
