"""change_starting_weight_to_array

Revision ID: c558ea5d4ef4
Revises: c4555ac3c4d7
Create Date: 2025-12-20 05:04:46.755157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c558ea5d4ef4'
down_revision = 'c4555ac3c4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_weights', sa.Text(), nullable=True))
        batch_op.alter_column('series_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('starting_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_weight', sa.FLOAT(), nullable=True))
        batch_op.alter_column('series_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('starting_weights')

    # ### end Alembic commands ###
