"""change rpe to string and add overall_rpe

Revision ID: c65fff35903f
Revises: 5e9610479e44
Create Date: 2025-12-22 16:12:23.566511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65fff35903f'
down_revision = '5e9610479e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rpe', sa.String(length=1), nullable=True))
        batch_op.alter_column('rpe',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.alter_column('rpe',
               existing_type=sa.String(length=1),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('overall_rpe')

    # ### end Alembic commands ###
