"""add video_url to exercises

Revision ID: e1f8a2b3c4d5
Revises: c65fff35903f
Create Date: 2025-12-22 18:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f8a2b3c4d5'
down_revision = 'c65fff35903f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_exercises', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
