"""add manufacturer and model to equipment

Revision ID: f2a3b4c5d6e7
Revises: e1f8a2b3c4d5
Create Date: 2025-12-22 21:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a3b4c5d6e7'
down_revision = 'e1f8a2b3c4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_equipment', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
