"""Initial migration

Revision ID: 303d78475b9f
Revises: 
Create Date: 2026-01-06 17:37:06.893549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303d78475b9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('body_metric_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.Column('left_arm', sa.Float(), nullable=True),
    sa.Column('right_arm', sa.Float(), nullable=True),
    sa.Column('left_thigh', sa.Float(), nullable=True),
    sa.Column('right_thigh', sa.Float(), nullable=True),
    sa.Column('left_calf', sa.Float(), nullable=True),
    sa.Column('right_calf', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_metric_history', schema=None) as batch_op:
        batch_op.create_index('idx_user_recorded', ['user_id', 'recorded_at'], unique=False)

    op.create_table('body_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pattern_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_type', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_equipment_name'), ['name'], unique=False)

    op.create_table('master_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('primary_muscle', sa.String(length=50), nullable=True),
    sa.Column('secondary_muscles', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_exercises_name'), ['name'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('target_body_fat', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('target_chest', sa.Float(), nullable=True),
    sa.Column('target_waist', sa.Float(), nullable=True),
    sa.Column('target_hips', sa.Float(), nullable=True),
    sa.Column('target_left_arm', sa.Float(), nullable=True),
    sa.Column('target_right_arm', sa.Float(), nullable=True),
    sa.Column('target_left_thigh', sa.Float(), nullable=True),
    sa.Column('target_right_thigh', sa.Float(), nullable=True),
    sa.Column('target_left_calf', sa.Float(), nullable=True),
    sa.Column('target_right_calf', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_gyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_unit', sa.String(length=10), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('current_body_fat', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.Column('left_arm', sa.Float(), nullable=True),
    sa.Column('right_arm', sa.Float(), nullable=True),
    sa.Column('left_thigh', sa.Float(), nullable=True),
    sa.Column('right_thigh', sa.Float(), nullable=True),
    sa.Column('left_calf', sa.Float(), nullable=True),
    sa.Column('right_calf', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('equipment_gym_association',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['user_gyms.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'gym_id')
    )
    op.create_table('equipment_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_equipment_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('progression_type', sa.String(length=20), nullable=False),
    sa.Column('weight_value', sa.Float(), nullable=True),
    sa.Column('plate_sizes', sa.Text(), nullable=True),
    sa.Column('stack_increment', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['user_gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['user_gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['user_gyms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_name', sa.String(length=50), nullable=True),
    sa.Column('is_deload', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.create_index('idx_program', ['program_id'], unique=False)

    op.create_table('user_exercise_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_equipment_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['master_equipment.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['equipment_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=50), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('has_superset', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['program_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.create_index('idx_week', ['week_id'], unique=False)

    op.create_table('program_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('series_type', sa.String(length=20), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['program_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_day_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['user_gyms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['program_instances.id'], ),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.create_index('idx_user_date', ['user_id', 'calendar_date'], unique=False)
        batch_op.create_index('idx_user_program_date', ['user_id', 'program_id', 'calendar_date'], unique=False)

    op.create_table('program_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('superset_position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(length=20), nullable=True),
    sa.Column('lift_time_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_time_seconds', sa.Integer(), nullable=True),
    sa.Column('starting_weights', sa.Text(), nullable=True),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['program_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.create_index('idx_series', ['series_id'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_day_id', sa.Integer(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['user_gyms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheduled_day_id'], ['scheduled_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_scheduled_day', ['scheduled_day_id'], unique=False)
        batch_op.create_index('idx_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('instance_exercise_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('program_exercise_id', sa.Integer(), nullable=False),
    sa.Column('custom_weights', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['program_instances.id'], ),
    sa.ForeignKeyConstraint(['program_exercise_id'], ['program_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rpe', sa.String(length=1), nullable=True),
    sa.Column('overall_rpe', sa.String(length=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['master_exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index('idx_exercise_completed', ['exercise_id', 'completed_at'], unique=False)
        batch_op.create_index('idx_session_exercise', ['workout_session_id', 'exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index('idx_session_exercise')
        batch_op.drop_index('idx_exercise_completed')

    op.drop_table('workout_sets')
    op.drop_table('instance_exercise_weights')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_started')
        batch_op.drop_index('idx_scheduled_day')

    op.drop_table('workout_sessions')
    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.drop_index('idx_series')

    op.drop_table('program_exercises')
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.drop_index('idx_user_program_date')
        batch_op.drop_index('idx_user_date')

    op.drop_table('scheduled_days')
    op.drop_table('program_series')
    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.drop_index('idx_week')

    op.drop_table('program_days')
    op.drop_table('exercise_equipment_variations')
    op.drop_table('user_exercise_preferences')
    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.drop_index('idx_program')

    op.drop_table('program_weeks')
    op.drop_table('program_shares')
    op.drop_table('program_instances')
    op.drop_table('gym_exercises')
    op.drop_table('gym_equipment')
    op.drop_table('exercise_equipment_mapping')
    op.drop_table('equipment_variations')
    op.drop_table('equipment_gym_association')
    op.drop_table('user_profiles')
    op.drop_table('user_gyms')
    op.drop_table('user_goals')
    op.drop_table('programs')
    with op.batch_alter_table('master_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_exercises_name'))

    op.drop_table('master_exercises')
    with op.batch_alter_table('master_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_equipment_name'))

    op.drop_table('master_equipment')
    op.drop_table('body_patterns')
    with op.batch_alter_table('body_metric_history', schema=None) as batch_op:
        batch_op.drop_index('idx_user_recorded')

    op.drop_table('body_metric_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
